const INVITATION_REWARD_GAME_COINS = 10;
const INVITATION_REWARD_CHAT_TOKENS = 25;
const INVITATION_REWARD_CALL_SECONDS = 3 * 60;

module.exports = {
  INVITATION_REWARD_GAME_COINS,
  INVITATION_REWARD_CHAT_TOKENS,
  INVITATION_REWARD_CALL_SECONDS,
};
