const WORD_BANK = [
  'APPLE',
  'HOUSE',
  'WATER',
  'LEARN',
  'STUDY',
  'WORLD',
  'HEART',
  'DREAM',
  'SMILE',
  'LIGHT',
  'NIGHT',
  'CHAIR',
  'PAPER',
  'GRADE',
  'PLANT',
  'BREAD',
  'CLOUD',
  'DANCE',
  'EARTH',
  'FLAME',
  'GRAPE',
  'HAPPY',
  'IMAGE',
  'JUICE',
  'KNIFE',
  'LEMON',
  'MUSIC',
  'OCEAN',
  'PEACE',
  'QUEEN',
  'RIVER',
  'STONE',
  'TABLE',
  'UNITY',
  'VOICE',
  'WATCH',
  'YOUTH',
  'ZEBRA',
  'BRAIN',
  'CLEAN',
  'DRINK',
  'ENJOY',
  'FOCUS',
  'GREEN',
  'HONOR',
  'IDEAL',
  'JOKER',
  'KNOWS',
  'LUNCH',
  'MAGIC',
  'ANGEL',
  'BEACH',
  'CANDY',
  'DELTA',
  'EAGLE',
  'FAITH',
  'GLOBE',
  'HOTEL',
  'IVORY',
  'JOLLY',
  'KARMA',
  'METAL',
  'NURSE',
  'OLIVE',
  'PIANO',
  'QUICK',
  'RADIO',
  'SWEET',
  'TIGER',
  'ULTRA',
  'VITAL',
  'WHEAT',
  'YACHT',
  'ZESTY',
  'AROMA',
  'BLAZE',
  'CRANE',
  'DRAFT',
  'ELBOW',
  'FROST',
  'GHOST',
  'HUMOR',
  'INBOX',
  'JAZZY',
  'KNEEL',
  'LAYER',
  'MANGO',
  'NOBLE',
  'OZONE',
  'PUPIL',
  'QUILT',
  'ROAST',
  'SPARK',
  'TULIP',
  'URBAN',
  'VIVID',
  'WHALE',
  'ZONAL',
  'ALBUM',
  'BLOOM',
];

const BOT_NAMES = [
  // Lucu
  'Mochi',
  'Bubu',
  'Neko酱',
  'Poyo',
  '豆豆',
  '喵喵',
  'Chibi',
  'Pickle',
  'Noodle',
  'Zuzu',
  // Japan (JP)
  'ゆき',
  'さくら',
  'そら',
  'もも',
  'ひなた',
  'りく',
  'あおい',
  'ゆずき',
  'みかん',
  'たろう',
  'けんた',
  'ななみ',
  'はると',
  'そうた',
  'めい',
  // Korea (KR)
  '지수',
  '민호',
  '유나',
  '준우',
  '하은',
  '서연',
  '민지',
  '다솜',
  '태양',
  '지원',
  '하윤',
  '서준',
  '은비',
  '예준',
  '수빈',
  // China (ZH)
  '小明',
  '美玲',
  '雨桐',
  '子涵',
  '浩然',
  '乐乐',
  '琪琪',
  '欣怡',
  '子轩',
  '晨曦',
  '一诺',
  '思远',
  '佳怡',
  '俊杰',
  '诗涵',
  // Lucu (latin)
  'NekoPaw',
  'DouDou',
  'MiaoMiao',
  'Beanie',
  'CocoPop',
  'Fizz',
  'Tibu',
  'Lulu',
  'Mimi',
  'Pip',
  // Jahil
  'TrollGemes',
  'NgakakBro',
  'KangTroll',
  'PrankFox',
  'EZpzKid',
  'LagKing',
  'SneakyCat',
  'CampLurker',
  'RushBNow',
  'Tiltless',
  'NoobHunter',
  'ChaosBean',
  'Mischief',
  'kentang',
  'yakultt',
  'aku takut',
  'who are u',
  'drakula',
  'u',
  'sapi',
  'mouuu',
  // Nama player asli
  'Minho97',
  'LunaPlays',
  'CloudNine',
  'NeoRider',
  'KaiStream',
  'ZetaFox',
  'RioGamer',
  'ArinVN',
  'DewiRP',
  'RizkyOne',
  'SkyWalker',
  'NightOwl',
  'PixelNova',
  'ZeroCool',
  'AquaWolf',
  'StormKid',
  'VexPlay',
  // Japan (romaji)
  'Yuki',
  'Sakura',
  'Sora',
  'Momo',
  'Hinata',
  'Haruto',
  'Nanami',
  'Yuzuki',
  'Aoi',
  'Kenta',
  'Riku',
  'Haru',
  'Yuzu',
  'Kenji',
  'Mei',
  'Kaito',
  'Rin',
  // Korea (romanized)
  'Jisoo',
  'Minho',
  'Yuna',
  'Junwoo',
  'Haeun',
  'Jiwoo',
  'Somin',
  'Dasom',
  'Taeyang',
  'Hayoon',
  'Seojun',
  // China (pinyin)
  'Meilin',
  'Xiaoyu',
  'Yichen',
  'Zihan',
  'Liying',
  'Yuxuan',
  'Chenhao',
  'Weilin',
  'Xinyi',
  'Boyang',
  'Jiahao',
  'Ruolan',
  'Mingyu',
  'Qiqi',
  'Lele',
  'YuTong',
  'ChenHao',
  'JiaYi',
  'HaoRan',
];

const isPlayerLikeName = name => {
  const trimmed = String(name || '').trim();
  return (
    trimmed.length >= 2 &&
    !/bot|computer|cpu|npc|ai|guest|player\d|master|bozz/i.test(trimmed)
  );
};

const { getSudowordWordBank } = require('./puzzleLocales');

const pickWord = (bank = WORD_BANK) => bank[Math.floor(Math.random() * bank.length)];

const buildChallenge = (learningLanguage = 'English') => {
  const localizedBank = getSudowordWordBank(learningLanguage);
  const bank =
    localizedBank && localizedBank.length > 0
      ? localizedBank
      : WORD_BANK;
  const word = pickWord(bank);
  const blankIndex = Math.floor(Math.random() * 5);
  const letters = word.split('').map((letter, index) => (index === blankIndex ? null : letter));
  return {
    id: `ch_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
    word,
    letters,
    blankIndex,
    answer: word[blankIndex],
  };
};

const serializeChallenge = challenge => ({
  id: challenge.id,
  letters: challenge.letters,
  blankIndex: challenge.blankIndex,
});

const randomBotName = used => {
  const validNames = BOT_NAMES.filter(isPlayerLikeName);
  let pool = validNames.filter(name => !used.has(name));
  if (pool.length === 0) {
    pool = validNames;
  }
  const pick = pool[Math.floor(Math.random() * pool.length)] || `桃桃${100 + used.size}`;
  used.add(pick);
  return pick;
};

const calcSudowordExp = (finalScore, rank = 5) => {
  const safeScore = Math.max(0, Number(finalScore) || 0);
  const base = Math.floor(safeScore / 10);
  const winBonus = rank === 1 ? 3 : rank === 2 ? 1 : 0;
  return Math.max(safeScore > 0 ? 1 : 0, base + winBonus);
};

module.exports = {
  MATCH_DURATION_MS: 5 * 60 * 1000,
  POINTS_CORRECT: 15,
  POINTS_WRONG: 5,
  calcSudowordExp,
  buildChallenge,
  serializeChallenge,
  randomBotName,
};
